"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.hasDocumentAccess = exports.getDocumentBuffer = exports.deleteDocument = exports.validateDownloadToken = exports.generateTempDownloadLink = exports.storeDocument = exports.deserializeEncrypted = exports.serializeEncrypted = exports.decryptFromString = exports.encryptToString = exports.decryptFields = exports.encryptFields = exports.decryptOptional = exports.encryptOptional = exports.decrypt = exports.encrypt = exports.getKenyaDate = exports.toKenyaTime = exports.getKenyaTimeMs = exports.getKenyaDateTime = exports.getKenyaTimeFormatted = exports.getKenyaTimeISO = void 0;
var timestamps_1 = require("./timestamps");
Object.defineProperty(exports, "getKenyaTimeISO", { enumerable: true, get: function () { return timestamps_1.getKenyaTimeISO; } });
Object.defineProperty(exports, "getKenyaTimeFormatted", { enumerable: true, get: function () { return timestamps_1.getKenyaTimeFormatted; } });
Object.defineProperty(exports, "getKenyaDateTime", { enumerable: true, get: function () { return timestamps_1.getKenyaDateTime; } });
Object.defineProperty(exports, "getKenyaTimeMs", { enumerable: true, get: function () { return timestamps_1.getKenyaTimeMs; } });
Object.defineProperty(exports, "toKenyaTime", { enumerable: true, get: function () { return timestamps_1.toKenyaTime; } });
Object.defineProperty(exports, "getKenyaDate", { enumerable: true, get: function () { return timestamps_1.getKenyaDate; } });
var encryption_1 = require("./encryption");
Object.defineProperty(exports, "encrypt", { enumerable: true, get: function () { return encryption_1.encrypt; } });
Object.defineProperty(exports, "decrypt", { enumerable: true, get: function () { return encryption_1.decrypt; } });
Object.defineProperty(exports, "encryptOptional", { enumerable: true, get: function () { return encryption_1.encryptOptional; } });
Object.defineProperty(exports, "decryptOptional", { enumerable: true, get: function () { return encryption_1.decryptOptional; } });
Object.defineProperty(exports, "encryptFields", { enumerable: true, get: function () { return encryption_1.encryptFields; } });
Object.defineProperty(exports, "decryptFields", { enumerable: true, get: function () { return encryption_1.decryptFields; } });
Object.defineProperty(exports, "encryptToString", { enumerable: true, get: function () { return encryption_1.encryptToString; } });
Object.defineProperty(exports, "decryptFromString", { enumerable: true, get: function () { return encryption_1.decryptFromString; } });
Object.defineProperty(exports, "serializeEncrypted", { enumerable: true, get: function () { return encryption_1.serializeEncrypted; } });
Object.defineProperty(exports, "deserializeEncrypted", { enumerable: true, get: function () { return encryption_1.deserializeEncrypted; } });
var documentProtection_1 = require("./documentProtection");
Object.defineProperty(exports, "storeDocument", { enumerable: true, get: function () { return documentProtection_1.storeDocument; } });
Object.defineProperty(exports, "generateTempDownloadLink", { enumerable: true, get: function () { return documentProtection_1.generateTempDownloadLink; } });
Object.defineProperty(exports, "validateDownloadToken", { enumerable: true, get: function () { return documentProtection_1.validateDownloadToken; } });
Object.defineProperty(exports, "deleteDocument", { enumerable: true, get: function () { return documentProtection_1.deleteDocument; } });
Object.defineProperty(exports, "getDocumentBuffer", { enumerable: true, get: function () { return documentProtection_1.getDocumentBuffer; } });
Object.defineProperty(exports, "hasDocumentAccess", { enumerable: true, get: function () { return documentProtection_1.hasDocumentAccess; } });
//# sourceMappingURL=index.js.map