-- Create body_releases table for tracking deceased body releases
CREATE TABLE IF NOT EXISTS body_releases (
    id INT PRIMARY KEY AUTO_INCREMENT,
    release_id VARCHAR(50) UNIQUE NOT NULL,
    tenant_slug VARCHAR(100) NOT NULL,
    admission_number VARCHAR(100),
    name_of_deceased VARCHAR(255),
    next_kin VARCHAR(255) NOT NULL,
    id_number VARCHAR(100) NOT NULL,
    tell_number VARCHAR(50) NOT NULL,
    relationship VARCHAR(100),
    date_of_removal DATE,
    time_of_removal VARCHAR(20),
    permit_number VARCHAR(100),
    mode_of_transport VARCHAR(100),
    terms_accepted BOOLEAN DEFAULT FALSE,
    everything_paid BOOLEAN DEFAULT FALSE,
    signature TEXT,
    staff_name VARCHAR(255),
    staff_signature TEXT,
    received_by VARCHAR(255),
    witness_name VARCHAR(255),
    items_returned TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_release_id (release_id),
    INDEX idx_tenant_slug (tenant_slug),
    INDEX idx_admission_number (admission_number),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
